services:
  x86-builder:
    platform: linux/amd64 
    build:
      context: .
      dockerfile: arch/x86/Dockerfile
    volumes:
      - ./arch/x86:/kernel/arch/x86
    environment:
      - TARGET=i686-elf
      - PREFIX=/opt/cross
    container_name: x86-cross

  arm64-builder:
    platform: linux/arm64
    build:
      context: .
      dockerfile: arch/arm64/Dockerfile
    volumes:
      - ./arch/arm64:/kernel/arch/arm64
    environment:
      - TARGET=arm-none-eabi
      - PREFIX=/opt/cross
    container_name: arm64-cross
