# Timeout in seconds that Limine will use before automatically booting.
timeout: 10

wallpaper: boot():/boot/cat.jpg
wallpaper_style: stretched
# Available styles: stretched, centered, tiled
backdrop: 000000
# Hex color code for the backdrop if style is centered (RRGGBB format)


# The entry name that will be displayed in the boot menu.
/Hubble OS
    # We use the Limine boot protocol.
    protocol: limine

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    kernel_path: boot():/boot/kernel.elf

    # Path to the initramfs module
    module_path: boot():/boot/initramfs.img
