# Scripts Makefile
.PHONY: img flash help qemu

SCRIPT_DIR := scripts

img:
	@sh $(SCRIPT_DIR)/img/make-image.sh

flash:
	@sh $(SCRIPT_DIR)/img/make-flash.sh

help:
	@sh $(SCRIPT_DIR)/cli/make-help.sh

qemu:
	@sh $(SCRIPT_DIR)/qemu/qemu.sh