#!/bin/bash
set -e

echo "🧰 Kernel Build System"
echo ""
echo "📦 Usage:"
echo "  make [TARGET] [ARCH=<arch>] [VARIABLE=value]"
echo ""
echo "🎯 Targets:"
echo "  all            - Build the kernel (default)"
echo "  build          - Build the kernel"
echo "  run            - Run the built kernel via QEMU (on host)"
echo "  qemu           - Run QEMU using current build "
echo "  img            - Build the kernel image (if implemented)"
echo "  flash          - Flash the kernel image to a USB device (if implemented)"
echo "  clean          - Remove all build output"
echo "  help           - Show this help message"
echo ""
echo "🐳 Docker Targets:"
echo "  docker-build   - Build the kernel inside Docker container"
echo "  docker-run     - Build in Docker, run kernel on host QEMU"
echo "  docker-clean   - Clean build output via Docker"
echo "  docker-<target>- Run any target inside Docker, e.g., 'make docker-img'"
echo ""
echo "🖥  Host-only Targets:"
echo "  host-run       - Run QEMU from host using current build output"
echo ""
echo "🛠  Variables:"
echo "  ARCH           - Target architecture (e.g. x86, arm64). Default: x86"
echo "  DOCKER_RUN     - Override Docker run command if needed"
echo ""
echo "✅ Available ARCH values:"
echo "  x86, arm64 (extendable in config/config.mk and docker-compose.yml)"
echo ""
